"""initial schema

Revision ID: acf3da774aa4
Revises: 
Create Date: 2026-07-06 07:50:23.316826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel  # noqa: F401  (autogenerate emits sqlmodel.sql.sqltypes.AutoString)


# revision identifiers, used by Alembic.
revision: str = 'acf3da774aa4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Postgres enum types must be created explicitly with checkfirst=True so a
    # round-trip upgrade/downgrade/upgrade works (table-drop does not drop the
    # enum type, and CREATE TABLE would otherwise try to re-create it).
    task_status_enum = postgresql.ENUM(
        'TODO', 'READY', 'IN_PROGRESS', 'REVIEW', 'DONE', 'BLOCKED', 'CANCELLED',
        name='taskstatus', create_type=False,
    )
    progress_kind_enum = postgresql.ENUM(
        'TEXT', 'DIFF', 'ARTIFACT_REF', 'ERROR', 'STATUS_CHANGE',
        name='progresskind', create_type=False,
    )
    task_status_enum.create(op.get_bind(), checkfirst=True)
    progress_kind_enum.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('repo_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('default_branch', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', task_status_enum, nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('claimed_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('claimed_at', sa.DateTime(), nullable=True),
    sa.Column('sort_order', sa.Float(), nullable=False),
    sa.Column('repo_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('base_branch', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('branch', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pr_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pr_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_claimed_by'), 'task', ['claimed_by'], unique=False)
    op.create_index(op.f('ix_task_status'), 'task', ['status'], unique=False)
    op.create_table('artifact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artifact_task_id'), 'artifact', ['task_id'], unique=False)
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('author', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('seen_by_agent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comment_created_at'), 'comment', ['created_at'], unique=False)
    op.create_index(op.f('ix_comment_task_id'), 'comment', ['task_id'], unique=False)
    op.create_table('progressevent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('agent', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kind', progress_kind_enum, nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_progressevent_created_at'), 'progressevent', ['created_at'], unique=False)
    op.create_index(op.f('ix_progressevent_task_id'), 'progressevent', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_progressevent_task_id'), table_name='progressevent')
    op.drop_index(op.f('ix_progressevent_created_at'), table_name='progressevent')
    op.drop_table('progressevent')
    op.drop_index(op.f('ix_comment_task_id'), table_name='comment')
    op.drop_index(op.f('ix_comment_created_at'), table_name='comment')
    op.drop_table('comment')
    op.drop_index(op.f('ix_artifact_task_id'), table_name='artifact')
    op.drop_table('artifact')
    op.drop_index(op.f('ix_task_status'), table_name='task')
    op.drop_index(op.f('ix_task_claimed_by'), table_name='task')
    op.drop_table('task')
    op.drop_table('project')
    # Drop enum types explicitly so a subsequent upgrade can re-create them.
    sa.Enum(name='taskstatus').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='progresskind').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
